VERSION=1.1.1.3
PACKAGE=zcs-lib-json-simple
MAINTAINER=Enrico Weigelt <enrico.weigelt@vnc.biz>
SECTION=base
ARCHITECTURE=All
PRIORITY=optional
DEPENDS=
DESCRIPTION=Simple JSON library
DISTPREFIX=$(TOPDIR)/dist
DISTDIR=$(DISTPREFIX)/$(PACKAGE)-$(VERSION)
DISTFILE=$(DISTPREFIX)/$(PACKAGE)-$(VERSION).tar.gz
JAVA?=java
JAR?=jar
JAVAC?=javac
IMAGE_ROOT=$(TOPDIR)/image
INSTALL_DIR=$(IMAGE_ROOT)/zimlets-install/$(PACKAGE)
REDMINE_UPLOAD_URL=https://redmine.vnc.biz/redmine/
REDMINE_UPLOAD_PROJECT=zcs-lib-json-simple
